service: serverlessdemo

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: v1
  region: eu-west-3
  iam:
    role: ${file(iam/IAMRole.yml):role}

functions:
  hello:
    handler: handler.hello
    environment:
      DYNAMODB_TABLE_NEWS: table_name_123
    events:
      - http:
          path: /hello
          method: GET
          cors: true
      - http:
          path: /json
          method: POST
          cors: true

resources: # CloudFormation template syntax
  Resources:
    newsTable: ${file(tables/newsTable.yml):newsTable}